export const AUTH = {
  ALERT: "ALERT",
  LOADING: "LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",
  USER: "USER",
};

export const EVENTS = {
  LOADING: "EVENTS_LOADING",
  CREATE_SUCCESS: "EVENTS_CREATE_SUCCESS",
  FETCH_SUCCESS: "EVENTS_FETCH_SUCCESS",
  CREATE_FAILURE: "EVENTS_CREATE_FAILURE",
  FETCH_FAILURE: "EVENTS_FETCH_FAILURE",
  DELETE_SUCCESS: "EVENTS_DELETE_SUCCESS",
  DELETE_FAILURE: "EVENTS_DELETE_FAILURE",
  UPDATE_SUCCESS: "EVENTS_UPDATE_SUCCESS",
  UPDATE_FAILURE: "EVENTS_UPDATE_FAILURE",
  ERROR: "EVENTS_ERROR",
};

export const INVITATIONS = {
  FETCH_SUCCESS: "INVITATIONS_FETCH_SUCCESS",
  FETCH_FAILURE: "INVITATIONS_FETCH_FAILURE",
  ACCEPT_INVITATION: "INVITATIONS_ACCEPT_INVITATION",
  DECLINE_INVITATION: "INVITATIONS_DECLINE_INVITATION",
  FETCH_INVITATION_LIST: "INVITATIONS_FETCH_INVITATION_LIST",
};
